const static String webpage = {
  "<!doctype html>"
  "<html lang=en>"
    "<head>"
      "<meta charset=utf-8 PAGE_REFRESH >"
      "<title>Modbus TCP/UDP &rlarr; RTU Gateway</title>"
      "<style>"
        "a {text-decoration:none;color:white}"
        "td:first-child {text-align:left;width:30%}"
        "th {text-align:left;background-color:#0067AC;color:white;padding:10px}"
        "table {width:100%}"
      "</style>"
    "</head>"
    "<body style='font-family:sans-serif'>"
      "<table height=100% style='position:absolute;top:0;bottom:0;left:0;right:0'>"
        "<tr style='height:10px'><th colspan=2>"
          "<h1 style='margin:0px'>Modbus TCP/UDP &rlarr; RTU Gateway</h1>"  // first row is header
        "<tr>"                                           // second row is left menu (first cell) and main page (second cell)
          "<th valign=top style=width:20%;padding:0px>"
          "<table>"
            "<tr>"
              "<th>"
                "<a href= status.htm> Current Status </a>"
            "<tr>"
              "<th>"
                "<a href= ip.htm> IP Settings </a>"
            "<tr>"
              "<th>"
                "<a href= tcp.htm> TCP/UDP Settings </a>"
            "<tr>"
              "<th>"
                "<a href= rtu.htm> RTU Settings </a>"
            "<tr>"
              "<th>"
                "<a href= tools.htm> Tools </a>"
          "</table>"
        "<td valign=top style=padding:0px>"
        " FUNCTION_DATA "
    "</body>"
  "</html>"
};


const static String finish_page = {
  "<table style=border-collapse:collapse>"
    "<tr>"
      "<th>"
      "Setting Finish"
      "<th>"
      "<th>"
    "<tr>"
      "<td>"
      "<td>"
      "<td><br><br>"
    "<tr>"
      "<td>"
      "<td>"
      "<td><br><br>"
    "<tr>"
      "<td>"
      "<td>"
      "<td> <a href=status.htm style='color: red; font-size: 30px;'> Retrun main page </a>"
  "</table>"
};

const static String status_page = {
  "<form method=post action=/status.htm>"
    "<table style=border-collapse:collapse>"
      "<tr>"
        "<th>"
        "System status"
        "<th>"
        "<th>"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"
      "<tr>"
        "<td>Microcontroller"
        "<td>=>"
        "<td>ESP32"
      "<tr>"
        "<td>Ethernet Chip"
        "<td>=>"
        "<td>DM9051"
      "<tr>"
        "<td>MAC Address"
        "<td>=>"
        "<td>MAC_ADDRESS"
      "<tr>"
        "<td>IP Address"
        "<td>=>"
        "<td>IP_ADDRESS"
      "<tr>"
        "<td>mDns name"
        "<td>=>"
        "<td>MDNS_NAME"      
      "<tr>"
        "<td>Run Time"
        "<td>=>"
        "<td> TIME_D days, TIME_H hours, TIME_M mins, TIME_S secs"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"

      "<tr>"
        "<td>ETH Data"
        "<td>=>"
        "<td>ETH_T_D Tx_bytes / ETH_R_D Rx_bytes (excl. WebUI)"
      "<tr>"
        "<td>"
        "<td>"
        "<td>ETH_ERROR_TCP Invalid TCP/UDP Request"
      "<tr>"
        "<td>"
        "<td>"
        "<td>TCP Port ETH_TCP_PORT"
      "<tr>"
        "<td>"
        "<td>"
        "<td>UDP Port ETH_UDP_PORT (UDP function =ETH_UDP_EN=)"
      "<tr>"
        "<td>"
        "<td>"
        "<td>RTU over TCP/DUP function =RTU_OVER_EN="
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"

      "<tr>"
        "<td>RTU Data"
        "<td>=>"
        "<td>RTU_T_D Tx_bytes / RTU_R_D Rx_bytes"
      "<tr>"
        "<td>"
        "<td>"
        "<td>RTU_SLAVE_OK Slave Responded"
      "<tr>"
        "<td>"
        "<td>"
        "<td>RTU_SLAVE_ERROR_0X Slave Responded with Error (Codes 1~8)"
      "<tr>"
        "<td>"
        "<td>"
        "<td>RTU_SLAVE_ERROR_0A Gateway Overloaded (Code 10)"
      "<tr>"
        "<td>"
        "<td>"
        "<td>RTU_SLAVE_ERROR_0B Slave Failed to Respond (Code 11)"
      "<tr>"
        "<td>"
        "<td>"
        "<td>RTU_ERROR_TIMEOUT Response Timeout"
      "<tr>"
        "<td>"
        "<td>"
        "<td>RTU_ERROR_RTU Invalid RTU Response"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"
      "<tr>"
        "<td>"
        "<td>"
        "<td><input type=submit name=cnt_reset value='reset_value'>"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"

      "RTU_DEVICE_CHECK"
    "</table>"
  "</form>"
};


const static String ip_page = {
  "<form method=post action=/ip_post>"
    "<table style=border-collapse:collapse>"
      "<tr>"
        "<th>"
        "IP Setting"
        "<th>"
        "<th>"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"
      "<tr>"
        "<td>DHCP EN"
        "<td>=>"
        "<td>"
          "<select  name=ip_dhcp_set >"
            "<option value='0' IP_DHCP_SELECT>Disable</option>"
            "<option value='1' IP_DHCP_SELECT>Enable</option>"
          "</select>"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"
      "<tr>"
        "<td>STATIC IP"
        "<td>=>"
        "<td>"
          "<input required type=number name=ip_sip_a min=1 max=255 value=IP_SIP_A>."
          "<input required type=number name=ip_sip_b min=0 max=255 value=IP_SIP_B>."
          "<input required type=number name=ip_sip_c min=0 max=255 value=IP_SIP_C>."
          "<input required type=number name=ip_sip_d min=0 max=255 value=IP_SIP_D>"
      "<tr>"
        "<td>SUBMASK"
        "<td>=>"
        "<td>"
          "<input required type=number name=ip_submask_a min=1 max=255 value=IP_SUBMASK_A>."
          "<input required type=number name=ip_submask_b min=0 max=255 value=IP_SUBMASK_B>."
          "<input required type=number name=ip_submask_c min=0 max=255 value=IP_SUBMASK_C>."
          "<input required type=number name=ip_submask_d min=0 max=255 value=IP_SUBMASK_D>"
      "<tr>"
        "<td>GATEWAY"
        "<td>=>"
        "<td>"
          "<input required type=number name=ip_geteway_a min=1 max=255 value=IP_GATEWAY_A>."
          "<input required type=number name=ip_geteway_b min=0 max=255 value=IP_GATEWAY_B>."
          "<input required type=number name=ip_geteway_c min=0 max=255 value=IP_GATEWAY_C>."
          "<input required type=number name=ip_geteway_d min=0 max=255 value=IP_GATEWAY_D>"          
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"
      "<tr>"
        "<td>"
        "<td>"
          "<input type=submit value='Save & Reboot'>"
        "<td>"
    "</table>"
  "</form>"
};


const static String tcp_page = {
  "<form method=post action=/tcp_post>"
    "<table style=border-collapse:collapse>"
      "<tr>"
        "<th>"
        "TCP/UDP Setting"
        "<th>"
        "<th>"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"
      "<tr>"
        "<td>TCP PORT"
        "<td>=>"
        "<td>"
          "<input required type=number name=tcp_tcp_port min=1 max=65535 value=TCP_TCP_P>"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"
      "<tr>"
        "<td>UDP EN"
        "<td>=>"
        "<td>"
          "<select  name=tcp_udp_set >"
            "<option value='0' TCP_UDP_SELECT>Disable</option>"
            "<option value='1' TCP_UDP_SELECT>Enable</option>"
          "</select>"
      "<tr>"
        "<td>UDP PORT"
        "<td>=>"
        "<td>"
          "<input required type=number name=tcp_udp_port min=1 max=65535 value=TCP_UDP_P>"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"
      "<tr>"
        "<td>TCP/UDP timeout"
        "<td>=>"
        "<td>"
          "<input required type=number name=tcp_timeout min=1 max=3600 value=TCP_TIME_OUT> sec"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"
      "<tr>"
        "<td>RTU OVER TCP/IP"
        "<td>=>"
        "<td>"
          "<select  name=tcp_rtu_set >"
            "<option value='0' TCP_RTU_SELECT>Disable</option>"
            "<option value='1' TCP_RTU_SELECT>Enable</option>"
          "</select>"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"
      "<tr>"
        "<td>"
        "<td>"
          "<input type=submit value='Save & Reboot'>"
        "<td>"
    "</table>"
  "</form>"
};


const static String rtu_page = {
  "<form method=post action=/rtu_post>"
    "<table style=border-collapse:collapse>"
      "<tr>"
        "<th>"
        "RTU Setting"
        "<th>"
        "<th>"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"
      "<tr>"
        "<td>Baud Rate"
        "<td>=>"
        "<td>"
          "<select  name=rtu_bps_set >"
            "<option value='0' RTU_BPS_SELECT>300</option>"
            "<option value='1' RTU_BPS_SELECT>600</option>"
            "<option value='2' RTU_BPS_SELECT>900</option>"
            "<option value='3' RTU_BPS_SELECT>1200</option>"
            "<option value='4' RTU_BPS_SELECT>2400</option>"
            "<option value='5' RTU_BPS_SELECT>4800</option>"
            "<option value='6' RTU_BPS_SELECT>9600</option>"
            "<option value='7' RTU_BPS_SELECT>19200</option>"
            "<option value='8' RTU_BPS_SELECT>38400</option>"
            "<option value='9' RTU_BPS_SELECT>57600</option>"
            "<option value='10' RTU_BPS_SELECT>115200</option>"
          "</select> bps"
      "<tr>"
        "<td>Data Bit"
        "<td>=>"
        "<td>"
          "<select  name=rtu_data_set >"
            "<option value='5' RTU_DATA_SELECT>5</option>"
            "<option value='6' RTU_DATA_SELECT>6</option>"
            "<option value='7' RTU_DATA_SELECT>7</option>"
            "<option value='8' RTU_DATA_SELECT>8</option>"
          "</select> bit"
      "<tr>"
        "<td>Parity"
        "<td>=>"
        "<td>"
          "<select  name=rtu_parity_set >"
            "<option value='0' RTU_PARITY_SELECT>None</option>"
            "<option value='2' RTU_PARITY_SELECT>Even</option>"
            "<option value='3' RTU_PARITY_SELECT>Odd</option>"
          "</select>"
      "<tr>"
        "<td>Stop Bit"
        "<td>=>"
        "<td>"
          "<select  name=rtu_stop_set >"
            "<option value='1' RTU_STOP_SELECT>1</option>"
            "<option value='3' RTU_STOP_SELECT>2</option>"
          "</select> bit"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"
      "<tr>"
        "<td>Slave_max_address"
        "<td>=>"
        "<td>"
          "<input required type=number name=rtu_sma min=1 max=247 value=RTU_SMA_VAL>"
      "<tr>"
        "<td>Inter-frame Delay"
        "<td>=>"
        "<td>"
          "<input required type=number name=rtu_ifd min=5 max=250 value=RTU_IFD_VAL> (5~250)ms"
      "<tr>"
        "<td>Response Timeout"
        "<td>=>"
        "<td>"
          "<input required type=number name=rtu_rt min=50 max=5000 value=RTU_RT_VAL> (50~5000)ms"
      "<tr>"
        "<td>Attempts"
        "<td>=>"
        "<td>"
          "<input required type=number name=rtu_attempts min=1 max=10 value=RTU_ATTEMPTS_VAL>"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"
      "<tr>"
        "<td>Boot up scan RTU savles"
        "<td>=>"
        "<td>"
          "<select  name=rtu_boot_scan_set >"
            "<option value='0' RTU_BS_SELECT>Disable</option>"
            "<option value='1' RTU_BS_SELECT>Enable</option>"
          "</select>"
      "<tr>"
        "<td>"
        "<td>"
          "<input type=submit value='Save & Reboot'>"
        "<td>"
    "</table>"
  "</form>"
};

const static String tools_page = {
  "<form method=post action=/tools_post>"
    "<table style=border-collapse:collapse>"
      "<tr>"
        "<th>"
        "Tools"
        "<th>"
        "<th>"
      "<tr>"
        "<td>"
        "<td>"
        "<td><br><br>"
      "<tr>"
        "<td>"
        "<td>"
          "<input type=submit value='load eerpom def & Reboot'>"
        "<td>"
    "</table>"
  "</form>"
};
